import { useEffect, useRef, useState, useCallback, useMemo } from "react";
import {
  View,
  Text,
  StyleSheet,
  Pressable,
  FlatList,
  Dimensions,
  ActivityIndicator,
  Alert,
  Modal,
} from "react-native";
import { useLocalSearchParams, router } from "expo-router";
import { useVideoPlayer, VideoView } from "expo-video";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { useLibraryStore } from "../../stores/library";
import { usePlaybackStore } from "../../stores/playback";
import { useConnectionStore } from "../../stores/connection";
import { api } from "../../services/api";
import { getVideoLocalPath } from "../../services/downloader";
import type { TranscriptSegment, Transcript, TranslateResult } from "../../types";

const { width: SCREEN_WIDTH } = Dimensions.get("window");
const VIDEO_HEIGHT = (SCREEN_WIDTH * 9) / 16;
const SEGMENT_HEIGHT = 56; // Approximate height of each segment row

export default function PlayerScreen() {
  const { id } = useLocalSearchParams<{ id: string }>();
  const libraryVideo = useLibraryStore((state) =>
    state.videos.find((v) => v.id === id)
  );
  const [currentTime, setCurrentTime] = useState(0);
  const [isPlaying, setIsPlaying] = useState(false);
  const [streamingTranscript, setStreamingTranscript] =
    useState<Transcript | null>(null);
  const [isLoadingTranscript, setIsLoadingTranscript] = useState(false);
  const [isDownloadingTranscript, setIsDownloadingTranscript] = useState(false);
  const transcriptListRef = useRef<FlatList>(null);
  const insets = useSafeAreaInsets();

  // Word definition lookup state
  const [selectedWord, setSelectedWord] = useState<string | null>(null);
  const [wordTranslation, setWordTranslation] = useState<TranslateResult | null>(null);
  const [isTranslating, setIsTranslating] = useState(false);
  const [isSavingWord, setIsSavingWord] = useState(false);
  const [wordSaved, setWordSaved] = useState(false);
  const [wordSegmentTimestamp, setWordSegmentTimestamp] = useState<number>(0);

  // Connection state for streaming
  const serverUrl = useConnectionStore((s) => s.serverUrl);
  const isConnectedToDesktop = useConnectionStore((s) => s.serverUrl !== null);

  // Playlist playback state
  const playlistId = usePlaybackStore((s) => s.playlistId);
  const playlistTitle = usePlaybackStore((s) => s.playlistTitle);
  const playlistVideos = usePlaybackStore((s) => s.playlistVideos);
  const currentIndex = usePlaybackStore((s) => s.currentIndex);
  const playNext = usePlaybackStore((s) => s.playNext);
  const playPrevious = usePlaybackStore((s) => s.playPrevious);
  const clearPlaylist = usePlaybackStore((s) => s.clearPlaylist);
  const hasNextVideo = usePlaybackStore((s) => s.hasNext());
  const hasPreviousVideo = usePlaybackStore((s) => s.hasPrevious());
  const setCurrentIndex = usePlaybackStore((s) => s.setCurrentIndex);
  const streamServerUrl = usePlaybackStore((s) => s.streamServerUrl);
  const isStreaming = usePlaybackStore((s) => s.isStreaming);
  const getStreamUrl = usePlaybackStore((s) => s.getStreamUrl);

  // Get video from playlist if streaming, otherwise from library
  const playlistVideo = playlistVideos.find((v) => v.id === id);
  const video = libraryVideo ?? playlistVideo;

  // Determine video source URL - resolve path dynamically to handle sandbox changes
  const localVideoPath = id ? getVideoLocalPath(id) : null;
  const videoSourceUrl =
    localVideoPath ?? (streamServerUrl && id ? getStreamUrl(id) : null);

  // Sync playlist index when video ID changes
  useEffect(() => {
    if (playlistId && id) {
      const index = playlistVideos.findIndex((v) => v.id === id);
      if (index >= 0 && index !== currentIndex) {
        setCurrentIndex(index);
      }
    }
  }, [id, playlistId, playlistVideos, currentIndex, setCurrentIndex]);

  // The effective server URL for fetching transcripts (desktop is source of truth)
  const effectiveServerUrl = useMemo(
    () => streamServerUrl || serverUrl || null,
    [streamServerUrl, serverUrl]
  );

  // Fetch transcript from desktop when connected (always, even for local videos)
  useEffect(() => {
    if (!id) return;
    const url = streamServerUrl || serverUrl;
    if (!url) {
      console.log("[Player] No server URL available for transcript fetch", {
        streamServerUrl,
        serverUrl,
      });
      return;
    }

    console.log("[Player] Fetching transcript from desktop", { url, videoId: id });
    setIsLoadingTranscript(true);
    api
      .getVideoTranscripts(url, id)
      .then((transcripts) => {
        console.log("[Player] Got transcripts:", transcripts.length);
        if (transcripts.length > 0) {
          // Use the first non-auto-generated transcript, or fall back to first available
          const preferred =
            transcripts.find((t) => !t.isAutoGenerated) ?? transcripts[0];
          setStreamingTranscript(preferred ?? null);
        } else {
          setStreamingTranscript(null);
        }
      })
      .catch((error) => {
        console.log("[Player] Failed to fetch transcript from desktop:", error);
        // Don't clear existing local transcript on failure
      })
      .finally(() => {
        setIsLoadingTranscript(false);
      });
  }, [id, streamServerUrl, serverUrl]); // Changed dependency array

  // Handle downloading transcript from desktop
  const handleDownloadTranscript = useCallback(async () => {
    const url = streamServerUrl || serverUrl;
    if (!id) return;
    if (!url) {
      Alert.alert(
        "Not Connected",
        "Connect to your desktop app first to download transcripts.",
        [{ text: "OK" }]
      );
      return;
    }

    setIsDownloadingTranscript(true);
    try {
      const result = await api.requestTranscriptDownload(url, id);
      console.log("[Player] Transcript download result:", result);

      if (result.success) {
        // Poll for transcript availability
        for (let attempt = 0; attempt < 5; attempt++) {
          await new Promise((resolve) => setTimeout(resolve, 3000));
          try {
            const transcripts = await api.getVideoTranscripts(url, id);
            if (transcripts.length > 0) {
              const preferred =
                transcripts.find((t) => !t.isAutoGenerated) ?? transcripts[0];
              setStreamingTranscript(preferred ?? null);
              break;
            }
          } catch {
            // Continue polling
          }
        }
      } else {
        Alert.alert(
          "Download Failed",
          result.message || "Could not download transcript",
          [{ text: "OK" }]
        );
      }
    } catch (error) {
      console.log("[Player] Failed to request transcript download:", error);
      Alert.alert(
        "Download Failed",
        "Could not connect to desktop to download transcript.",
        [{ text: "OK" }]
      );
    } finally {
      setIsDownloadingTranscript(false);
    }
  }, [id, streamServerUrl, serverUrl]); // Changed dependency array

  // Handle word tap for definition lookup
  const handleWordPress = useCallback(
    async (word: string, segmentTimestamp: number) => {
      const url = effectiveServerUrl;
      if (!url || !id) return;

      // Clean the word
      const cleanWord = word.replace(/[.,!?;:()[\]'"…\-–—]/g, "").trim();
      if (!cleanWord || cleanWord.length < 2) return;

      setSelectedWord(cleanWord);
      setWordTranslation(null);
      setIsTranslating(true);
      setWordSaved(false);
      setWordSegmentTimestamp(segmentTimestamp);

      try {
        const result = await api.translateWord(url, cleanWord, "en", {
          videoId: id,
          timestampSeconds: segmentTimestamp,
        });
        setWordTranslation(result);
      } catch (e) {
        console.log("[Player] Translation failed:", e);
        setWordTranslation(null);
      } finally {
        setIsTranslating(false);
      }
    },
    [effectiveServerUrl, id]
  );

  // Handle saving a word
  const handleSaveWord = useCallback(async () => {
    const url = effectiveServerUrl;
    if (!url || !wordTranslation?.translationId || isSavingWord) return;

    setIsSavingWord(true);
    try {
      const result = await api.saveWord(url, wordTranslation.translationId);
      if (result.success) {
        setWordSaved(true);
      }
    } catch (e) {
      console.log("[Player] Save word failed:", e);
      Alert.alert("Error", "Could not save word");
    } finally {
      setIsSavingWord(false);
    }
  }, [effectiveServerUrl, wordTranslation, isSavingWord]);

  const closeWordModal = useCallback(() => {
    setSelectedWord(null);
    setWordTranslation(null);
    setWordSaved(false);
  }, []);

  const player = useVideoPlayer(videoSourceUrl || "", (player) => {
    player.loop = false;
    player.timeUpdateEventInterval = 0.5; // Emit timeUpdate every 0.5 seconds
    player.staysActiveInBackground = true;
    player.showNowPlayingNotification = true;
    player.play();
  });

  useEffect(() => {
    if (!player) return;

    const subscription = player.addListener("playingChange", (event) => {
      setIsPlaying(event.isPlaying);
    });

    const timeSubscription = player.addListener(
      "timeUpdate",
      (event) => {
        setCurrentTime(event.currentTime);
      }
    );

    // Auto-advance to next video in playlist when current video ends
    const endSubscription = player.addListener("playToEnd", () => {
      if (playlistId && hasNextVideo) {
        const nextVideo = playNext();
        if (nextVideo) {
          router.replace(`/player/${nextVideo.id}`);
        }
      }
    });

    return () => {
      subscription.remove();
      timeSubscription.remove();
      endSubscription.remove();
    };
  }, [player, playlistId, hasNextVideo, playNext]);

  const handleSegmentPress = (segment: TranscriptSegment) => {
    if (player) {
      player.currentTime = segment.start;
    }
  };

  const handleBackPress = useCallback(() => {
    // Clear playlist context when manually going back
    if (playlistId) {
      clearPlaylist();
    }
    router.back();
  }, [playlistId, clearPlaylist]);

  const handlePreviousPress = useCallback(() => {
    const prevVideo = playPrevious();
    if (prevVideo) {
      router.replace(`/player/${prevVideo.id}`);
    }
  }, [playPrevious]);

  const handleNextPress = useCallback(() => {
    const nextVideo = playNext();
    if (nextVideo) {
      router.replace(`/player/${nextVideo.id}`);
    }
  }, [playNext]);

  // Use remote transcript if available, otherwise fall back to local
  const transcript = streamingTranscript ?? libraryVideo?.transcript;

  const getCurrentSegmentIndex = () => {
    if (!transcript?.segments) return -1;
    const time = currentTime;
    for (let i = transcript.segments.length - 1; i >= 0; i--) { // Changed loop direction
      if (time >= transcript.segments[i].start) return i;
    }
    return -1;
  };

  const currentSegmentIndex = getCurrentSegmentIndex();

  // Debug: log time updates
  useEffect(() => {
    if (currentTime > 0) {
      console.log(
        `[Player] time=${currentTime.toFixed(1)}s, segment=${currentSegmentIndex}, playing=${isPlaying}`
      );
    }
  }, [Math.floor(currentTime), currentSegmentIndex, isPlaying]);

  // Auto-scroll transcript
  useEffect(() => {
    if (currentSegmentIndex >= 0 && transcriptListRef.current) { // Removed isPlaying from condition
      try { // Added try-catch
        transcriptListRef.current.scrollToIndex({
          index: currentSegmentIndex,
          animated: true,
          viewPosition: 0.3,
        });
      } catch {
        // Ignore scroll errors
      }
    }
  }, [currentSegmentIndex]); // Removed isPlaying from dependencies

  const ITEM_HEIGHT = 56; // Defined ITEM_HEIGHT
  const getItemLayout = (_: unknown, index: number) => ({
    length: ITEM_HEIGHT, // Used ITEM_HEIGHT
    offset: ITEM_HEIGHT * index, // Used ITEM_HEIGHT
    index,
  });

  const handleScrollToIndexFailed = (info: {
    index: number;
    highestMeasuredFrameIndex: number;
    averageItemLength: number; // Kept original type for safety, though not used in snippet
  }) => {
    const wait = new Promise<void>((resolve) => setTimeout(resolve, 100)); // Changed to Promise
    wait.then(() => {
      if (transcriptListRef.current && info.index >= 0) {
        try { // Added try-catch
          transcriptListRef.current.scrollToIndex({
            index: Math.min(info.index, info.highestMeasuredFrameIndex), // Adjusted index calculation
            animated: true,
          });
        } catch {
          // Ignore
        }
      }
    });
  };

  // Render tappable words in a segment
  const renderTappableSegment = useCallback(
    (text: string, segmentStart: number) => {
      if (!isConnectedToDesktop) {
        return <Text style={styles.segmentText}>{text}</Text>;
      }

      const words = text.split(/(\s+)/);
      return (
        <Text style={styles.segmentText}>
          {words.map((word, i) => {
            if (/^\s+$/.test(word)) {
              return word; // Return whitespace as-is
            }
            return (
              <Text
                key={i}
                style={styles.tappableWord}
                onPress={() => handleWordPress(word, segmentStart)}
              >
                {word}
              </Text>
            );
          })}
        </Text>
      );
    },
    [isConnectedToDesktop, handleWordPress]
  );

  if (!video) { // Changed condition
    return (
      <View style={[styles.container, { paddingTop: insets.top }]}>
        <Pressable
          style={styles.backButton}
          onPress={() => {
            clearPlaylist(); // Added clearPlaylist
            router.back();
          }}
        >
          <Text style={styles.backButtonText}>← Back</Text>
        </Pressable>
        <View style={styles.noTranscript}>
          <Text style={styles.errorText}>Video not found</Text>
        </View>
      </View>
    );
  }

  return (
    <View style={styles.container}>
      <View style={[styles.header, { paddingTop: insets.top }]}>
        <View style={styles.headerRow}>
          <Pressable
            onPress={() => { // Modified onPress
              clearPlaylist();
              router.back();
            }}
            style={styles.backButton}
          >
            <Text style={styles.backButtonText}>← Back</Text>
          </Pressable>
          {playlistId && (
            <View style={styles.playlistControls}> {/* Kept playlistControls, assuming navButtons was a typo */}
              <Pressable
                style={[
                  styles.navButton,
                  !hasPreviousVideo && styles.navButtonDisabled,
                ]}
                onPress={() => { // Modified onPress
                  const prev = playPrevious();
                  if (prev?.id) {
                    router.replace(`/player/${prev.id}`);
                  }
                }}
                disabled={!hasPreviousVideo}
              >
                <Text
                  style={[
                    styles.navButtonText,
                    !hasPreviousVideo && styles.navButtonTextDisabled,
                  ]}
                >
                  ⏮
                </Text>
              </Pressable>
              <Pressable
                style={[
                  styles.navButton,
                  !hasNextVideo && styles.navButtonDisabled,
                ]}
                onPress={handleNextPress}
                disabled={!hasNextVideo}
              >
                <Text
                  style={[
                    styles.navButtonText,
                    !hasNextVideo && styles.navButtonTextDisabled,
                  ]}
                >
                  ⏭
                </Text>
              </Pressable>
            </View>
          )}
        </View>
        {playlistId && playlistTitle && (
          <View style={styles.playlistIndicator}>
            <Text style={styles.playlistIndicatorText}>
              Playing {currentIndex + 1} of {playlistVideos.length} • {playlistTitle}
            </Text>
          </View>
        )}
      </View>

      <VideoView player={player} style={styles.video} />

      <View style={styles.infoContainer}>
        <Text style={styles.title} numberOfLines={2}>
          {video.title}
        </Text>
        <View style={styles.channelRow}>
          <Text style={styles.channel}>{video.channelTitle}</Text>
          {!localVideoPath && (streamServerUrl || isStreaming) && (
            <View style={styles.streamingBadge}>
              <Text style={styles.streamingBadgeText}>Streaming</Text>
            </View>
          )}
        </View>
      </View>

      {isLoadingTranscript ? (
        <View style={[styles.noTranscript, { paddingBottom: insets.bottom }]}>
          <Text style={styles.noTranscriptText}>Loading transcript...</Text>
        </View>
      ) : transcript?.segments && transcript.segments.length > 0 ? (
        <View style={styles.transcriptContainer}>
          <View style={styles.transcriptHeaderRow}>
            <Text style={styles.transcriptHeader}>Transcript</Text>
            {isConnectedToDesktop && (
              <Text style={styles.tapHintText}>Tap a word to translate</Text>
            )}
          </View>
          <FlatList
            ref={transcriptListRef}
            data={transcript.segments}
            keyExtractor={(_, index) => index.toString()}
            getItemLayout={getItemLayout}
            onScrollToIndexFailed={handleScrollToIndexFailed}
            contentContainerStyle={{ paddingBottom: insets.bottom }}
            initialNumToRender={20}
            maxToRenderPerBatch={10}
            windowSize={10}
            renderItem={({ item, index }) => (
              <Pressable
                style={[
                  styles.segment,
                  index === currentSegmentIndex && styles.segmentActive,
                ]}
                onPress={() => handleSegmentPress(item)}
              >
                <Text style={styles.segmentTime}>
                  {formatTime(item.start)}
                </Text>
                <View style={{ flex: 1 }}>
                  {renderTappableSegment(item.text, item.start)}
                </View>
              </Pressable>
            )}
          />
        </View>
      ) : (
        <View style={[styles.noTranscript, { paddingBottom: insets.bottom }]}>
          <Text style={styles.noTranscriptText}>
            No transcript available for this video
          </Text>
          <Pressable
            style={[
              styles.downloadTranscriptButton,
              isDownloadingTranscript && styles.downloadTranscriptButtonDisabled,
            ]}
            onPress={handleDownloadTranscript}
            disabled={isDownloadingTranscript}
          >
            {isDownloadingTranscript ? (
              <>
                <ActivityIndicator size="small" color="#fff" />
                <Text style={styles.downloadTranscriptButtonText}>
                  Downloading...
                </Text>
              </>
            ) : (
              <Text style={styles.downloadTranscriptButtonText}>
                Download Transcript from Desktop
              </Text>
            )}
          </Pressable>
        </View>
      )}

      {/* Word Definition Modal */}
      <Modal
        visible={selectedWord !== null}
        transparent
        animationType="slide"
        onRequestClose={closeWordModal}
      >
        <Pressable style={styles.modalOverlay} onPress={closeWordModal}>
          <View style={styles.modalContent} onStartShouldSetResponder={() => true}>
            <View style={styles.modalHandle} />
            <Text style={styles.modalWord}>{selectedWord}</Text>

            {isTranslating ? (
              <View style={styles.modalLoadingContainer}>
                <ActivityIndicator size="small" color="#e94560" />
                <Text style={styles.modalLoadingText}>Translating...</Text>
              </View>
            ) : wordTranslation?.success ? (
              <>
                <Text style={styles.modalTranslation}>
                  {wordTranslation.translatedText}
                </Text>
                {wordTranslation.detectedLang && (
                  <Text style={styles.modalLang}>
                    Detected: {wordTranslation.detectedLang}
                  </Text>
                )}

                {wordSaved ? (
                  <View style={styles.savedBadge}>
                    <Text style={styles.savedBadgeText}>✓ Saved to My Words</Text>
                  </View>
                ) : (
                  <Pressable
                    style={styles.saveWordButton}
                    onPress={handleSaveWord}
                    disabled={isSavingWord}
                  >
                    {isSavingWord ? (
                      <ActivityIndicator size="small" color="#fff" />
                    ) : (
                      <Text style={styles.saveWordButtonText}>
                        + Save to My Words
                      </Text>
                    )}
                  </Pressable>
                )}
              </>
            ) : (
              <Text style={styles.modalError}>
                Could not translate this word
              </Text>
            )}

            <Pressable style={styles.modalCloseButton} onPress={closeWordModal}>
              <Text style={styles.modalCloseButtonText}>Close</Text>
            </Pressable>
          </View>
        </Pressable>
      </Modal>
    </View>
  );
}

function formatTime(seconds: number): string {
  const mins = Math.floor(seconds / 60);
  const secs = Math.floor(seconds % 60);
  return `${mins}:${secs.toString().padStart(2, "0")}`;
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#0f0f23",
  },
  header: {
    backgroundColor: "#0f0f23",
  },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  backButton: {
    padding: 16,
  },
  backButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "500",
  },
  playlistControls: {
    flexDirection: "row",
    alignItems: "center",
    paddingRight: 12,
    gap: 8,
  },
  navButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#1a1a2e",
    justifyContent: "center",
    alignItems: "center",
  },
  navButtonDisabled: {
    backgroundColor: "#0f0f23",
  },
  navButtonText: {
    fontSize: 18,
  },
  navButtonTextDisabled: {
    opacity: 0.3,
  },
  playlistIndicator: {
    paddingHorizontal: 16,
    paddingBottom: 8,
  },
  playlistIndicatorText: {
    color: "#e94560",
    fontSize: 12,
    fontWeight: "500",
  },
  video: {
    width: SCREEN_WIDTH,
    height: VIDEO_HEIGHT,
    backgroundColor: "#000",
  },
  infoContainer: {
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#1a1a2e",
  },
  title: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "600",
    marginBottom: 4,
  },
  channel: {
    color: "#a0a0a0",
    fontSize: 14,
  },
  channelRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  streamingBadge: {
    backgroundColor: "#9333ea",
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 10,
  },
  streamingBadgeText: {
    color: "#fff",
    fontSize: 11,
    fontWeight: "600",
  },
  transcriptContainer: {
    flex: 1,
    backgroundColor: "#16213e",
  },
  transcriptHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#1a1a2e",
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  transcriptHeader: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "600",
  },
  tapHintText: {
    color: "#666",
    fontSize: 11,
    fontStyle: "italic",
  },
  segment: {
    flexDirection: "row",
    padding: 12,
    minHeight: SEGMENT_HEIGHT,
    borderBottomWidth: 1,
    borderBottomColor: "#1a1a2e",
  },
  segmentActive: {
    backgroundColor: "#1a1a2e",
  },
  segmentTime: {
    color: "#e94560",
    fontSize: 12,
    fontWeight: "500",
    width: 45,
    marginRight: 12,
  },
  segmentText: {
    flex: 1,
    color: "#a0a0a0",
    fontSize: 14,
    lineHeight: 20,
  },
  segmentTextActive: {
    color: "#fff",
  },
  tappableWord: {
    color: "#a0a0a0",
    fontSize: 14,
    lineHeight: 20,
  },
  noTranscript: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  noTranscriptText: {
    color: "#666",
    fontSize: 14,
    marginBottom: 16,
  },
  downloadTranscriptButton: {
    backgroundColor: "#e94560",
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 8,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginTop: 8,
  },
  downloadTranscriptButtonDisabled: {
    backgroundColor: "#555",
  },
  downloadTranscriptButtonText: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "600",
  },
  errorText: {
    color: "#e94560",
    fontSize: 16,
    textAlign: "center",
    marginTop: 100,
  },
  // Word definition modal styles
  modalOverlay: {
    flex: 1,
    justifyContent: "flex-end",
    backgroundColor: "rgba(0, 0, 0, 0.5)",
  },
  modalContent: {
    backgroundColor: "#16213e",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 24,
    paddingBottom: 40,
    alignItems: "center",
    minHeight: 250,
  },
  modalHandle: {
    width: 40,
    height: 4,
    backgroundColor: "#333",
    borderRadius: 2,
    marginBottom: 20,
  },
  modalWord: {
    color: "#fff",
    fontSize: 28,
    fontWeight: "bold",
    marginBottom: 16,
    textAlign: "center",
  },
  modalTranslation: {
    color: "#e94560",
    fontSize: 22,
    fontWeight: "600",
    marginBottom: 8,
    textAlign: "center",
  },
  modalLang: {
    color: "#666",
    fontSize: 12,
    marginBottom: 20,
  },
  modalLoadingContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginVertical: 20,
  },
  modalLoadingText: {
    color: "#a0a0a0",
    fontSize: 14,
  },
  modalError: {
    color: "#666",
    fontSize: 14,
    marginVertical: 20,
  },
  saveWordButton: {
    backgroundColor: "#059669",
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 8,
    marginTop: 8,
    minWidth: 160,
    alignItems: "center",
  },
  saveWordButtonText: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "600",
  },
  savedBadge: {
    backgroundColor: "rgba(5, 150, 105, 0.15)",
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 8,
    marginTop: 8,
  },
  savedBadgeText: {
    color: "#059669",
    fontSize: 14,
    fontWeight: "600",
  },
  modalCloseButton: {
    marginTop: 20,
    paddingVertical: 10,
    paddingHorizontal: 30,
  },
  modalCloseButtonText: {
    color: "#666",
    fontSize: 14,
  },
});
