import { useEffect, useRef, useState, useCallback } from "react";
import {
  View,
  Text,
  StyleSheet,
  Pressable,
  FlatList,
  Dimensions,
} from "react-native";
import { useLocalSearchParams, router } from "expo-router";
import { useVideoPlayer, VideoView } from "expo-video";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { useLibraryStore } from "../../stores/library";
import { usePlaybackStore } from "../../stores/playback";
import { useConnectionStore } from "../../stores/connection";
import { api } from "../../services/api";
import { getVideoLocalPath } from "../../services/downloader";
import type { TranscriptSegment, Transcript } from "../../types";

const { width: SCREEN_WIDTH } = Dimensions.get("window");
const VIDEO_HEIGHT = (SCREEN_WIDTH * 9) / 16;
const SEGMENT_HEIGHT = 56; // Approximate height of each segment row

export default function PlayerScreen() {
  const { id } = useLocalSearchParams<{ id: string }>();
  const libraryVideo = useLibraryStore((state) =>
    state.videos.find((v) => v.id === id)
  );
  const [currentTime, setCurrentTime] = useState(0);
  const [isPlaying, setIsPlaying] = useState(false);
  const [streamingTranscript, setStreamingTranscript] =
    useState<Transcript | null>(null);
  const [isLoadingTranscript, setIsLoadingTranscript] = useState(false);
  const transcriptListRef = useRef<FlatList>(null);
  const insets = useSafeAreaInsets();

  // Connection state for streaming
  const serverUrl = useConnectionStore((s) => s.serverUrl);

  // Playlist playback state
  const playlistId = usePlaybackStore((s) => s.playlistId);
  const playlistTitle = usePlaybackStore((s) => s.playlistTitle);
  const playlistVideos = usePlaybackStore((s) => s.playlistVideos);
  const currentIndex = usePlaybackStore((s) => s.currentIndex);
  const playNext = usePlaybackStore((s) => s.playNext);
  const playPrevious = usePlaybackStore((s) => s.playPrevious);
  const clearPlaylist = usePlaybackStore((s) => s.clearPlaylist);
  const hasNextVideo = usePlaybackStore((s) => s.hasNext());
  const hasPreviousVideo = usePlaybackStore((s) => s.hasPrevious());
  const setCurrentIndex = usePlaybackStore((s) => s.setCurrentIndex);
  const streamServerUrl = usePlaybackStore((s) => s.streamServerUrl);
  const isStreaming = usePlaybackStore((s) => s.isStreaming);
  const getStreamUrl = usePlaybackStore((s) => s.getStreamUrl);

  // Get video from playlist if streaming, otherwise from library
  const playlistVideo = playlistVideos.find((v) => v.id === id);
  const video = libraryVideo ?? playlistVideo;

  // Determine video source URL - resolve path dynamically to handle sandbox changes
  const localVideoPath = id ? getVideoLocalPath(id) : null;
  const videoSourceUrl =
    localVideoPath ?? (streamServerUrl && id ? getStreamUrl(id) : null);

  // Sync playlist index when video ID changes
  useEffect(() => {
    if (playlistId && id) {
      const index = playlistVideos.findIndex((v) => v.id === id);
      if (index >= 0 && index !== currentIndex) {
        setCurrentIndex(index);
      }
    }
  }, [id, playlistId, playlistVideos, currentIndex, setCurrentIndex]);

  // Fetch transcript when streaming (not from local library)
  useEffect(() => {
    if (!localVideoPath && id && (streamServerUrl || serverUrl)) {
      const url = streamServerUrl || serverUrl;
      if (!url) return;

      setIsLoadingTranscript(true);
      api
        .getVideoTranscripts(url, id)
        .then((transcripts) => {
          // Use the first non-auto-generated transcript, or fall back to first available
          const preferred =
            transcripts.find((t) => !t.isAutoGenerated) ?? transcripts[0];
          setStreamingTranscript(preferred ?? null);
        })
        .catch((error) => {
          console.log("[Player] Failed to fetch streaming transcript:", error);
          setStreamingTranscript(null);
        })
        .finally(() => {
          setIsLoadingTranscript(false);
        });
    }
  }, [id, localVideoPath, streamServerUrl, serverUrl]);

  const player = useVideoPlayer(videoSourceUrl || "", (player) => {
    player.loop = false;
    player.timeUpdateEventInterval = 0.5; // Emit timeUpdate every 0.5 seconds
    player.staysActiveInBackground = true;
    player.showNowPlayingNotification = true;
    player.play();
  });

  useEffect(() => {
    if (!player) return;

    const subscription = player.addListener("playingChange", (event) => {
      setIsPlaying(event.isPlaying);
    });

    const timeSubscription = player.addListener(
      "timeUpdate",
      (event) => {
        setCurrentTime(event.currentTime);
      }
    );

    // Auto-advance to next video in playlist when current video ends
    const endSubscription = player.addListener("playToEnd", () => {
      if (playlistId && hasNextVideo) {
        const nextVideo = playNext();
        if (nextVideo) {
          router.replace(`/player/${nextVideo.id}`);
        }
      }
    });

    return () => {
      subscription.remove();
      timeSubscription.remove();
      endSubscription.remove();
    };
  }, [player, playlistId, hasNextVideo, playNext]);

  const handleSegmentPress = (segment: TranscriptSegment) => {
    if (player) {
      player.currentTime = segment.start;
    }
  };

  const handleBackPress = useCallback(() => {
    // Clear playlist context when manually going back
    if (playlistId) {
      clearPlaylist();
    }
    router.back();
  }, [playlistId, clearPlaylist]);

  const handlePreviousPress = useCallback(() => {
    const prevVideo = playPrevious();
    if (prevVideo) {
      router.replace(`/player/${prevVideo.id}`);
    }
  }, [playPrevious]);

  const handleNextPress = useCallback(() => {
    const nextVideo = playNext();
    if (nextVideo) {
      router.replace(`/player/${nextVideo.id}`);
    }
  }, [playNext]);

  // Use local transcript or streaming transcript
  const transcript = libraryVideo?.transcript ?? streamingTranscript;

  const getCurrentSegmentIndex = () => {
    if (!transcript?.segments) return -1;
    const index = transcript.segments.findIndex(
      (seg, i, arr) =>
        currentTime >= seg.start &&
        (i === arr.length - 1 || currentTime < arr[i + 1].start)
    );
    return index;
  };

  const currentSegmentIndex = getCurrentSegmentIndex();

  // Debug: log time updates
  useEffect(() => {
    if (currentTime > 0) {
      console.log(
        `[Player] time=${currentTime.toFixed(1)}s, segment=${currentSegmentIndex}, playing=${isPlaying}`
      );
    }
  }, [Math.floor(currentTime), currentSegmentIndex, isPlaying]);

  // Auto-scroll transcript
  useEffect(() => {
    if (currentSegmentIndex >= 0 && transcriptListRef.current && isPlaying) {
      transcriptListRef.current.scrollToIndex({
        index: currentSegmentIndex,
        animated: true,
        viewPosition: 0.3,
      });
    }
  }, [currentSegmentIndex, isPlaying]);

  const getItemLayout = (_: unknown, index: number) => ({
    length: SEGMENT_HEIGHT,
    offset: SEGMENT_HEIGHT * index,
    index,
  });

  const handleScrollToIndexFailed = (info: {
    index: number;
    highestMeasuredFrameIndex: number;
    averageItemLength: number;
  }) => {
    // Retry scrolling after a short delay
    setTimeout(() => {
      if (transcriptListRef.current && info.index >= 0) {
        transcriptListRef.current.scrollToIndex({
          index: info.index,
          animated: true,
          viewPosition: 0.3,
        });
      }
    }, 100);
  };

  if (!video || !videoSourceUrl) {
    return (
      <View style={[styles.container, { paddingTop: insets.top }]}>
        <Pressable onPress={handleBackPress} style={styles.backButton}>
          <Text style={styles.backButtonText}>← Back</Text>
        </Pressable>
        <Text style={styles.errorText}>
          {!video ? "Video not found" : "No video source available"}
        </Text>
      </View>
    );
  }

  return (
    <View style={styles.container}>
      <View style={[styles.header, { paddingTop: insets.top }]}>
        <View style={styles.headerRow}>
          <Pressable onPress={handleBackPress} style={styles.backButton}>
            <Text style={styles.backButtonText}>← Back</Text>
          </Pressable>
          {playlistId && (
            <View style={styles.playlistControls}>
              <Pressable
                style={[
                  styles.navButton,
                  !hasPreviousVideo && styles.navButtonDisabled,
                ]}
                onPress={handlePreviousPress}
                disabled={!hasPreviousVideo}
              >
                <Text
                  style={[
                    styles.navButtonText,
                    !hasPreviousVideo && styles.navButtonTextDisabled,
                  ]}
                >
                  ⏮
                </Text>
              </Pressable>
              <Pressable
                style={[
                  styles.navButton,
                  !hasNextVideo && styles.navButtonDisabled,
                ]}
                onPress={handleNextPress}
                disabled={!hasNextVideo}
              >
                <Text
                  style={[
                    styles.navButtonText,
                    !hasNextVideo && styles.navButtonTextDisabled,
                  ]}
                >
                  ⏭
                </Text>
              </Pressable>
            </View>
          )}
        </View>
        {playlistId && playlistTitle && (
          <View style={styles.playlistIndicator}>
            <Text style={styles.playlistIndicatorText}>
              Playing {currentIndex + 1} of {playlistVideos.length} • {playlistTitle}
            </Text>
          </View>
        )}
      </View>

      <VideoView player={player} style={styles.video} />

      <View style={styles.infoContainer}>
        <Text style={styles.title} numberOfLines={2}>
          {video.title}
        </Text>
        <View style={styles.channelRow}>
          <Text style={styles.channel}>{video.channelTitle}</Text>
          {!localVideoPath && (streamServerUrl || isStreaming) && (
            <View style={styles.streamingBadge}>
              <Text style={styles.streamingBadgeText}>Streaming</Text>
            </View>
          )}
        </View>
      </View>

      {isLoadingTranscript ? (
        <View style={[styles.noTranscript, { paddingBottom: insets.bottom }]}>
          <Text style={styles.noTranscriptText}>Loading transcript...</Text>
        </View>
      ) : transcript?.segments && transcript.segments.length > 0 ? (
        <View style={styles.transcriptContainer}>
          <Text style={styles.transcriptHeader}>Transcript</Text>
          <FlatList
            ref={transcriptListRef}
            data={transcript.segments}
            keyExtractor={(_, index) => index.toString()}
            getItemLayout={getItemLayout}
            onScrollToIndexFailed={handleScrollToIndexFailed}
            contentContainerStyle={{ paddingBottom: insets.bottom }}
            initialNumToRender={20}
            maxToRenderPerBatch={10}
            windowSize={10}
            renderItem={({ item, index }) => (
              <Pressable
                style={[
                  styles.segment,
                  index === currentSegmentIndex && styles.segmentActive,
                ]}
                onPress={() => handleSegmentPress(item)}
              >
                <Text style={styles.segmentTime}>
                  {formatTime(item.start)}
                </Text>
                <Text
                  style={[
                    styles.segmentText,
                    index === currentSegmentIndex && styles.segmentTextActive,
                  ]}
                >
                  {item.text}
                </Text>
              </Pressable>
            )}
          />
        </View>
      ) : (
        <View style={[styles.noTranscript, { paddingBottom: insets.bottom }]}>
          <Text style={styles.noTranscriptText}>
            No transcript available for this video
          </Text>
        </View>
      )}
    </View>
  );
}

function formatTime(seconds: number): string {
  const mins = Math.floor(seconds / 60);
  const secs = Math.floor(seconds % 60);
  return `${mins}:${secs.toString().padStart(2, "0")}`;
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#0f0f23",
  },
  header: {
    backgroundColor: "#0f0f23",
  },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  backButton: {
    padding: 16,
  },
  backButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "500",
  },
  playlistControls: {
    flexDirection: "row",
    alignItems: "center",
    paddingRight: 12,
    gap: 8,
  },
  navButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#1a1a2e",
    justifyContent: "center",
    alignItems: "center",
  },
  navButtonDisabled: {
    backgroundColor: "#0f0f23",
  },
  navButtonText: {
    fontSize: 18,
  },
  navButtonTextDisabled: {
    opacity: 0.3,
  },
  playlistIndicator: {
    paddingHorizontal: 16,
    paddingBottom: 8,
  },
  playlistIndicatorText: {
    color: "#e94560",
    fontSize: 12,
    fontWeight: "500",
  },
  video: {
    width: SCREEN_WIDTH,
    height: VIDEO_HEIGHT,
    backgroundColor: "#000",
  },
  infoContainer: {
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#1a1a2e",
  },
  title: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "600",
    marginBottom: 4,
  },
  channel: {
    color: "#a0a0a0",
    fontSize: 14,
  },
  channelRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  streamingBadge: {
    backgroundColor: "#9333ea",
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 10,
  },
  streamingBadgeText: {
    color: "#fff",
    fontSize: 11,
    fontWeight: "600",
  },
  transcriptContainer: {
    flex: 1,
    backgroundColor: "#16213e",
  },
  transcriptHeader: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "600",
    padding: 12,
    backgroundColor: "#1a1a2e",
  },
  segment: {
    flexDirection: "row",
    padding: 12,
    minHeight: SEGMENT_HEIGHT,
    borderBottomWidth: 1,
    borderBottomColor: "#1a1a2e",
  },
  segmentActive: {
    backgroundColor: "#1a1a2e",
  },
  segmentTime: {
    color: "#e94560",
    fontSize: 12,
    fontWeight: "500",
    width: 45,
    marginRight: 12,
  },
  segmentText: {
    flex: 1,
    color: "#a0a0a0",
    fontSize: 14,
    lineHeight: 20,
  },
  segmentTextActive: {
    color: "#fff",
  },
  noTranscript: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  noTranscriptText: {
    color: "#666",
    fontSize: 14,
  },
  errorText: {
    color: "#e94560",
    fontSize: 16,
    textAlign: "center",
    marginTop: 100,
  },
});
