export interface TranscriptSegment {
  start: number;
  end: number;
  text: string;
}

export interface Transcript {
  language: string;
  isAutoGenerated?: boolean;
  segments: TranscriptSegment[];
}

export interface Video {
  id: string;
  title: string;
  channelTitle: string;
  duration: number;
  thumbnailUrl?: string;
  localPath?: string;
  transcriptPath?: string;
  transcript?: Transcript;
  // Multiple transcripts for different languages
  transcripts?: Transcript[];
}

export interface RemoteVideo {
  id: string;
  title: string;
  channelTitle: string;
  duration: number;
  fileSize: number;
  hasTranscript: boolean;
  thumbnailUrl?: string;
  // Available transcript languages
  availableLanguages?: string[];
}

export interface ServerInfo {
  name: string;
  version: string;
  videoCount: number;
  // Optional for legacy desktop builds that predate protocol negotiation.
  syncProtocolVersion?: number;
  minSupportedMobileSyncProtocolVersion?: number;
}

export interface VideoMeta {
  id: string;
  title: string;
  channelTitle: string;
  duration: number;
  description?: string | null;
  transcript?: Transcript;
  // Multiple transcripts from server
  transcripts?: Transcript[];
}

// P2P Sharing Types
export interface DiscoveredPeer {
  name: string;
  host: string;
  port: number;
  videoCount: number;
}

export interface PeerVideo {
  id: string;
  title: string;
  channelTitle: string;
  duration: number;
  hasTranscript: boolean;
}

export interface TransferProgress {
  videoId: string;
  title: string;
  progress: number;
  status: "pending" | "downloading" | "completed" | "failed";
}

// Sync API Types
export interface RemoteChannel {
  channelId: string;
  channelTitle: string;
  thumbnailUrl: string | null;
  videoCount: number;
  lastUpdatedAt?: string | null;
}

export interface RemotePlaylist {
  playlistId: string;
  title: string;
  thumbnailUrl: string | null;
  itemCount: number | null;
  channelId: string | null;
  type: "channel" | "custom";
  downloadedCount: number;
}

export interface RemoteVideoWithStatus {
  id: string;
  title: string;
  channelTitle: string;
  duration: number;
  thumbnailUrl: string | null;
  downloadStatus: "completed" | "downloading" | "queued" | "pending" | null;
  downloadProgress: number | null;
  fileSize: number | null;
}

export interface RemoteFavorite {
  id: string;
  entityType: "video" | "custom_playlist" | "channel_playlist";
  entityId: string;
  video?: RemoteVideoWithStatus;
  playlist?: RemotePlaylist;
}

export interface ServerDownloadStatus {
  videoId: string;
  status: "queued" | "downloading" | "completed" | "failed" | "pending" | null;
  progress: number | null;
  error: string | null;
}

// Subscriptions (YouTube subscribed channels)
export interface RemoteSubscription {
  channelId: string;
  channelTitle: string;
  thumbnailUrl: string | null;
  videoCount: number;
}

// My Lists (user-created collections)
export interface RemoteMyList {
  id: string;
  name: string;
  itemCount: number;
  thumbnailUrl: string | null;
}

// Browse tabs for the home screen
export type BrowseTab = "mylists" | "channels" | "playlists" | "subscriptions";

// Flashcard sync types
export interface RemoteFlashcard {
  id: string;
  videoId: string | null;
  frontContent: string;
  backContent: string;
  contextText: string | null;
  cardType: "basic" | "cloze" | "concept";
  tags: string[];
  clozeContent: string | null;
  difficulty: number;
  nextReviewAt: string | null;
  reviewCount: number;
  easeFactor: number;
  interval: number;
  createdAt: string;
  updatedAt: string | null;
}

// Saved word sync types
export interface RemoteSavedWord {
  id: string;
  notes: string | null;
  reviewCount: number;
  lastReviewedAt: number | null;
  createdAt: number;
  sourceText: string;
  translatedText: string;
  sourceLang: string;
  targetLang: string;
  translationId: string;
}

// Translation result from desktop proxy
export interface TranslateResult {
  success: boolean;
  translatedText: string;
  translationId: string;
  detectedLang: string;
  fromCache: boolean;
}
